development:
  adapter: mysql
  database: my_test
  host: localhost
  username: root
  password: root
test:
  adapter: mysql
  database: login_test
  host: localhost
  username: root
  password: 1234

production:
  adapter: mysql
  database: login_production
  host: localhost
  username: root
  password: 1234 db/production.sqlite3
